version: "3.8"

services:
  mysql-db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test-db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
